//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 HoldingHands.rc 使用
//
#define IDOK2                           2
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_SERVER_STATU                 101
#define ID_HOST_COUNT                   102
#define ID_UPLOAD_SPEED                 103
#define ID_DOWNLOAD_SPEED               104
#define ID_CUR_DATE                     105
#define ID_HOST_SELECTED                106
#define ID_PROCESS_COUNT                107
#define ID_CPU_USAGE                    108
#define ID_MEM_USAGE                    109
#define IDR_MAINFRAME                   128
#define IDR_HoldingHandsTYPE            130
#define IDD_EDITCMT_DLG                 310
#define IDD_GETSTR_DLG                  310
#define IDD_FILETRANS                   311
#define IDD_URL_INPUT                   312
#define IDD_MNDD_DLG                    313
#define IDD_SELECT_FILE_DLG             314
#define IDD_CHAT_NAME                   317
#define IDD_CHAT_DLG                    318
#define IDD_FM_DLG                      319
#define IDR_FM_TOOLBAR                  320
#define IDR_FM_MENU                     322
#define IDI_FM_DEL                      328
#define IDI_FM_GO                       329
#define IDI_FM_NEWFOLDER                330
#define IDI_FM_REFRESH                  331
#define IDI_FM_SEARCH                   332
#define IDI_FM_UP                       333
#define IDI_FM_VIEW                     334
#define IDD_FM_SEARCH_DLG               337
#define IDR_RD_MENU                     338
#define IDD_DIALOG1                     339
#define IDD_DIALOG2                     340
#define IDD_AUDIODLG                    340
#define IDD_BUILD                       341
#define IDD_DIALOG3                     342
#define IDD_SETTING                     342
#define IDR_DATA1                       343
#define IDR_DATA2                       344
#define IDD_KBD_LOG                     345
#define IDR_CAM_MENU                    346
#define IDR_SOCKS_PROXY_MENU            348
#define IDD_SOCKS_ADDR                  349
#define IDR_PROCESS_MANAGER             350
#define IDR_GROUP_MANAGER               351
#define IDD_DLG_NEW_GROUP               352
#define IDC_EDIT1                       1000
#define IDC_TRANS_PROGRESS              1001
#define IDC_EDIT3                       1001
#define IDC_TOTAL_PROGRESS              1002
#define IDC_CURRENT_FILE                1004
#define IDC_DOWNLOAD_PROGRESS           1005
#define IDC_CURRENT_FILE2               1005
#define IDC_CURRENT_PROGRESS            1005
#define IDC_MFCSHELLTREE1               1006
#define IDC_MFCSHELLLIST1               1007
#define IDC_EDIT2                       1010
#define IDC_LIST1                       1011
#define IDC_EDIT4                       1011
#define IDC_BUTTON1                     1013
#define IDC_CHECK1                      1014
#define IDC_BUTTON2                     1015
#define IDC_CHECK2                      1015
#define IDC_CHECK3                      1016
#define IDC_URL                         1022
#define IDC_FILE_NAME                   1023
#define IDC_RICHEDIT21                  1023
#define IDC_PROGRESS                    1024
#define IDC_IPADDRESS1                  1024
#define IDC_IPADDRESS2                  1025
#define ID_MAIN                         32771
#define ID_MAIN_STARTSERVER             32772
#define ID_MAIN_SETTINGS                32773
#define ID_MAIN_BUILD                   32774
#define ID_MAIN_EXIT                    32775
#define ID_OPERATION                    32776
#define ID_OPERATION_REMOTEDESKTOP      32777
#define ID_OPERATION_KEYBOARD           32778
#define ID_OPERATION_CAMERA             32779
#define ID_OPERATION_MICROPHONE         32780
#define ID_OPERATION_FILEMANAGER        32781
#define ID_OPERATION_PROCESSMANAGER     32782
#define ID_OPERATION_REGEDIT            32783
#define ID_OPERATION_CMD                32784
#define ID_OPERATION_CHATBOX            32785
#define ID_OPERATION_SESSION            32786
#define ID_OPERATION_UPLOADMODULE       32787
#define ID_SESSION_DISCONNECT           32788
#define ID_SESSION_UNINSTALL            32789
#define ID_SESSION_POWER                32790
#define ID_POWER_SHUTDOWN               32792
#define ID_UPLOADMODULE_FROMDISK        32793
#define ID_UPLOADMODULE_FROMURL         32794
#define ID_VIEW                         32795
#define ID_VIEW_CLIENTLIST              32796
#define ID_VIEW_LOG                     32797
#define ID_POWER_REBOOT                 32798
#define ID_OPERATION_EDITCOMMENT        32799
#define ID_OPERATION_BLOCKINPUT         32800
#define ID_FM_UP                        32801
#define ID_FM_SEARCH                    32802
#define ID_FM_NEWFOLDER                 32803
#define ID_FM_VIEW                      32804
#define ID_MENU_NEWFOLDER               32805
#define ID_MENU_RUNFILE                 32806
#define ID_MENU_UPLOAD                  32807
#define ID_UPLOAD_FROMDISK              32808
#define ID_UPLOAD_FROMURL               32809
#define ID_MENU_DOWNLOAD                32810
#define ID_MENU_RENAME                  32811
#define ID_MENU_DELETE                  32812
#define ID_MENU_CUT                     32813
#define ID_MENU_COPY                    32814
#define ID_MENU_PASTE                   32815
#define ID_FM_DEL                       32816
#define ID_FM_REFRESH                   32817
#define ID_FM_GO                        32818
#define ID_VIEW_ICON                    32819
#define ID_VIEW_LIST32820               32820
#define ID_VIEW_DETAILEDINFORMATION     32821
#define ID_RUNFILE_HIDE                 32822
#define ID_RUNFILE_NORMAL               32823
#define ID_DISPLAY_STRETCH              32824
#define ID_DISPLAY_TILE                 32825
#define ID_CAPTURE_MOUSE                32826
#define ID_CAPTURE_TRANSPARENTWINDOW    32827
#define ID_CONTROL_MOUSE                32828
#define ID_CONTROL_KEYBOARD             32829
#define ID_DISPLAY_MAXFPS               32830
#define ID_MAXFPS_10                    32831
#define ID_MAXFPS_20                    32832
#define ID_MAXFPS_30                    32833
#define ID_MAXFPS_NOLIMIT               32834
#define ID_SESSION_RESTART              32835
#define ID_OPERATION_DOWNLOADANDEXEC    32836
#define ID_DISPLAY_FULLSCREEN           32837
#define ID_OTHER_SCREENSHOT             32838
#define ID_OTHER_RECORD                 32839
#define ID_OPERATION_WINDOWMANAGER      32840
#define ID_CAPTURE_RECORD               32841
#define ID_CAPTURE_SCREENSHOT           32842
#define ID_CAPTURE_START                32843
#define ID_DISPLAY_FULLSCREEN32844      32844
#define ID_DISPLAY_FULLSCREEN32845      32845
#define ID_OPERATION_UTILS              32846
#define ID_UTILS_COPYTOSTARTUP          32847
#define ID_UTILS_ADDTO                  32848
#define ID_UTILS_DOWNLOADANDEXEC        32849
#define ID_DISPLAY_QUALITY              32850
#define ID_QUALITY_LOW                  32851
#define ID_QUALITY_HIGH                 32852
#define ID_MAIN_STARTPROXY              32853
#define ID_MAIN_STOP                    32854
#define ID_VER_SOCKS                    32855
#define ID_VER_SOCKS5                   32856
#define ID_VER_SOCKS4                   32857
#define ID_OPERATION_PROXY              32858
#define ID_PROXY_SOCKSPROXY             32859
#define ID_SESSION_DISCONNECT32860      32860
#define ID_SESSION_EXIT                 32861
#define ID_LOG_CLEAR                    32862
#define ID_CONNECTIONS_DISCONNECTALL    32863
#define ID_CONNECTIONS_DISCONNECT       32864
#define ID_UTILS_OPENWEBPAGE            32865
#define ID_MAIN_KILLPROCESS             32866
#define ID_PROCESS_KILLPROCESS          32867
#define ID_MAIN_PARENTPROCESS           32868
#define ID_PROCESS                      32869
#define ID_PROCESS_PARENT               32870
#define ID_OPERATION_REMOTEDESKTOP32871 32871
#define ID_REMOTEDESKTOP_GDI            32872
#define ID_REMOTEDESKTOP_DXGICAPTURE    32873
#define ID_REMOTEDESKTOP_DXGI           32874
#define ID_MAIN_ADDGROUP                32875
#define ID_MAIN_REMOVECURRENTGROUP      32876
#define ID_OPERATION_MODIFYGROUP        32877
#define ID_VIEW_LOGVIEW                 32878
#define ID_VIEW_STATUSBAR               32879

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        353
#define _APS_NEXT_COMMAND_VALUE         32880
#define _APS_NEXT_CONTROL_VALUE         1027
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
