#ifndef CAMERA_COMMON_H
#define CAMERA_COMMON_H

#define CAMERA			('C'|('A'<<8)|('M'<<16)|('E')<<24)

enum CAMERA_EVENT
{
	CAMERA_DEVICELIST,
	CAMERA_START,
	CAMERA_VIDEOSIZE,
	CAMERA_STOP,
	CAMERA_STOP_OK,
	CAMERA_FRAME,
	CAMERA_ERROR,
	CAMERA_GETFRAME,
	CAMERA_SCREENSHOT
};

#endif