#ifndef FILE_MANAGER_COMMON_H
#define FILE_MANAGER_COMMON_H


#define FILE_MANAGER	('F'|('M'<<8)|('G')<<16|('R'<<24))

enum  FILE_MANAGER_EVENT
{
	FILE_MGR_CHDIR,
	FILE_MGR_CHDIR_RET,
	FILE_MGR_GETLIST,
	FILE_MGR_GETLIST_RET,
	FILE_MGR_UP,
	FILE_MGR_REFRESH,
	FILE_MGR_SEARCH,
	FILE_MGR_UPLOADFROMDISK,
	FILE_MGR_UPLOADFRURL,
	FILE_MGR_DOWNLOAD,
	FILE_MGR_RUNFILE_NORMAL,
	FILE_MGR_RUNFILE_HIDE,
	FILE_MGR_NEWFOLDER,
	FILE_MGR_RENAME,
	FILE_MGR_DELETE,
	FILE_MGR_COPY,
	FILE_MGR_CUT,
	FILE_MGR_PASTE,
	FILE_MGR_NEW_FOLDER_SUCCESS,
	FILE_MGR_ERROR
};

#endif