#ifndef FILE_TRANSFER_H
#define FILE_TRANSFER_H

#define MINIFILETRANS	('M'|('N'<<8)|('F')<<16|('T')<<24)


#define MNFT_DUTY_SENDER			(0xabcdef11)
#define MNFT_DUTY_RECEIVER			(~MNFT_DUTY_SENDER)
#define MNFT_STATU_SUCCESS			(0x01010101)
#define MNFT_STATU_FAILED			(0x02020202)

enum FILE_TRANSFER_EVENT
{
	//
	MNFT_INIT,
	MNFT_TRANS_INFO_GET,
	MNFT_TRANS_INFO_RPL,
	MNFT_FILE_INFO_GET,
	MNFT_FILE_INFO_RPL,
	MNFT_FILE_DATA_CHUNK_GET,
	MNFT_FILE_DATA_CHUNK_RPL,
	MNFT_FILE_TRANS_FINISHED,
	MNFT_TRANS_FINISHED
};

#endif