#ifndef KBLOG_COMMON_H
#define KBLOG_COMMON_H


#define KBLG	('K'|('B'<<8)|('L'<<16)|('G'<<24))
#define EXIT_HOOK 0x10086


enum KBLOG_EVENT
{
	KEYBD_LOG_GET_LOG,
	KEYBD_LOG_DATA_APPEND,
	KEYBD_LOG_ERROR,
	KEYBD_LOG_INITINFO,
	KEYBD_LOG_SETOFFLINERCD,
	KEYBD_LOG_GETPLUGS,
	KEYBD_LOG_PLUGS,
	KEYBD_LOG_CLEAN,
	KEYBD_LOG_DATA_NEW
};


#endif