#ifndef RD_COMMON_H
#define RD_COMMON_H



#define REMOTEDESKTOP	('R'|('D'<<8)|('T'<<16)|('P'<<24))

#define REMOTEDESKTOP_FLAG_CAPTURE_MOUSE		(0x1)
#define REMOTEDESKTOP_FLAG_CAPTURE_TRANSPARENT	(0x2)


#define QUALITY_LOW		0
#define QUALITY_HIGH	2

#define FLAG_DRAW_MOUSE 0x1
#define FLAG_CAPTURE_TRANSPARENTWND 0x2


enum RD_EVENT
{
	REMOTEDESKTOP_MONITORS,					//monitors;
	REMOTEDESKTOP_START_CAPTURE,			//start capture
	REMOTEDESKTOP_DESKSIZE,					//start capture response.

	REMOTEDESKTOP_NEXT_FRAME,
	REMOTEDESKTOP_FRAME,
	
	REMOTEDESKTOP_ERROR,
	REMOTEDESKTOP_CTRL,
	
	REMOTEDESKTOP_SETFLAG,
	REMOTEDESKTOP_SET_CLIPBOARDTEXT,
	REMOTEDESKTOP_GET_BMP_FILE,
	REMOTEDESKTOP_BMP_FILE
};


#endif